import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class MediaService {
  // Original images container
  private baseUrl = 'https://davendestaticimages.blob.core.windows.net/davendesiteimages/';

  // Thumbnails container (generated by Azure Function)
  private thumbBaseUrl = 'https://davendestaticimages.blob.core.windows.net/davendesiteimages-thumbnails/';

  constructor() {
    // Optional: Load from environment or config file if needed
    // this.baseUrl = this.loadBaseUrlFromConfig();
  }

  /**
   * Get media URL
   * @param path - Path to the image/video file
   * @param thumbnail - If true, returns thumbnail URL; if false, returns full-size URL (default: false)
   * @returns Full URL to the media file
   */
  url(path: string, thumbnail: boolean = false): string {
    const normalized = (path || '').replace(/\\/g, '/');

    if (thumbnail) {
      // Return thumbnail URL: RadianceParty.JPEG → RadianceParty_thumb.JPEG
      const parts = normalized.split('.');
      const thumbName = parts[0] + '_thumb.' + parts.slice(1).join('.');
      const normalizedBase = this.thumbBaseUrl.endsWith('/') ? this.thumbBaseUrl : this.thumbBaseUrl + '/';
      return normalizedBase + thumbName;
    }

    // Return full-size image URL (default)
    const normalizedBase = this.baseUrl.endsWith('/') ? this.baseUrl : this.baseUrl + '/';
    return normalizedBase + normalized;
  }
}
