import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class MediaService {
  // Original images container
  private baseUrl = 'https://davendestaticimages.blob.core.windows.net/davendesiteimages/';

  // Thumbnails container (generated by Azure Function)
  private thumbBaseUrl = 'https://davendestaticimages.blob.core.windows.net/davendesiteimages-thumbnails/';

  constructor() {
    // Optional: Load from environment or config file if needed
    // this.baseUrl = this.loadBaseUrlFromConfig();
  }

  /**
   * Get media URL
   * @param path - Path to the image/video file
   * @param thumbnail - If true, returns thumbnail URL; if false, returns full-size URL (default: false)
   * @returns Full URL to the media file
   */
  url(path: string, thumbnail: boolean = false): string {
    const normalized = (path || '').replace(/\\/g, '/');

    if (thumbnail) {
      // For videos, thumbnail is a .jpg file with the same base name
      const videoExtensions = ['.mp4', '.mov', '.avi', '.wmv', '.mkv', '.webm'];
      const isVideo = videoExtensions.some(ext => normalized.toLowerCase().endsWith(ext));
      
      if (isVideo) {
        // Video thumbnail: video.mp4 -> video.jpg
        const baseName = normalized.substring(0, normalized.lastIndexOf('.'));
        const normalizedBase = this.thumbBaseUrl.endsWith('/') ? this.thumbBaseUrl : this.thumbBaseUrl + '/';
        return normalizedBase + baseName + '.jpg';
      }
      
      // Image thumbnail: same filename in thumbnails container
      const normalizedBase = this.thumbBaseUrl.endsWith('/') ? this.thumbBaseUrl : this.thumbBaseUrl + '/';
      return normalizedBase + normalized;
    }

    // Return full-size image/video URL (default)
    const normalizedBase = this.baseUrl.endsWith('/') ? this.baseUrl : this.baseUrl + '/';
    return normalizedBase + normalized;
  }
}
